import type { TourConfig } from '../types';

export const gahrdQuickTour: TourConfig = {
  id: 'gahrd_quick_tour',
  role: 'gahrd',
  title: 'Quick Tour GA / HRD',
  description: 'Panduan pengelolaan operasional armada, penugasan driver, dan koordinasi kendaraan dinas.',
  type: 'quick_tour',
  steps: [
    {
      id: 'step_gahrd_dashboard',
      title: '1. GA / HRD Dashboard',
      description: 'Selamat datang di Dashboard GA/HRD! Halaman ini memuat ringkasan ketersediaan armada dan kesiapan driver.',
      targetSelector: '[data-guide="gahrd-dashboard-overview"]',
      route: '/gahrd/dashboard',
      position: 'bottom',
    },
    {
      id: 'step_gahrd_recent_requests',
      title: '2. Permintaan Terbaru',
      description: 'Tabel ini menampilkan permohonan kendaraan terbaru dari staf yang disetujui Kadep dan siap diverifikasi.',
      targetSelector: '[data-guide="gahrd-recent-table"]',
      route: '/gahrd/dashboard',
      position: 'top',
    },
    {
      id: 'step_gahrd_requests',
      title: '3. Verifikasi & Penugasan Armada',
      description: 'Kelola dan tentukan unit kendaraan dinas serta pengemudi yang dialokasikan untuk permohonan dinas.',
      targetSelector: '[data-guide="gahrd-requests"]',
      route: '/gahrd/requests',
      position: 'right',
    },
    {
      id: 'step_driver_assignment',
      title: '4. Driver Availability & Assignment',
      description: 'Pantau status ketersediaan driver (Available / On Trip) dan lakukan alokasi penugasan driver ke permohonan.',
      targetSelector: '[data-guide="driver-assignment"]',
      route: '/gahrd/driver',
      position: 'right',
    },
    {
      id: 'step_vehicle_assignment',
      title: '5. Vehicle Management',
      description: 'Kelola inventaris armada mobil dinas, kondisi odometer, foto STNK, serta ketersediaan unit.',
      targetSelector: '[data-guide="vehicle-assignment"]',
      route: '/admin/vehicles',
      position: 'right',
    },
    {
      id: 'step_gahrd_schedule',
      title: '6. Operational Calendar',
      description: 'Lihat matriks kalender penugasan kendaraan untuk menghindari bentrok jadwal perjalanan dinas.',
      targetSelector: '[data-guide="gahrd-schedule"]',
      route: '/gahrd/calendar',
      position: 'right',
    },
    {
      id: 'step_gahrd_history',
      title: '7. Reports & History',
      description: 'Akses laporan lengkap penggunaan armada, pengeluaran sewa eksternal, dan arsip riwayat perjalanan.\n\nAnda siap mengelola armada perusahaan!',
      targetSelector: '[data-guide="gahrd-history"]',
      route: '/gahrd/history',
      position: 'right',
    },
  ],
};
