import type { TourConfig } from '../types';

export const approverQuickTour: TourConfig = {
  id: 'approver_quick_tour',
  role: 'approver',
  title: 'Quick Tour Manager Approver',
  description: 'Panduan persetujuan pengajuan armada kendaraan dinas untuk Kepala Departemen.',
  type: 'quick_tour',
  steps: [
    {
      id: 'step_approver_dashboard',
      title: '1. Approver Dashboard',
      description: 'Selamat datang di Dashboard Departemen! Di sini Anda dapat memantau permohonan kendaraan dari staf Anda.',
      targetSelector: '[data-guide="approver-dashboard-header"]',
      route: '/approver/dashboard',
      position: 'bottom',
    },
    {
      id: 'step_approver_stats',
      title: '2. Kartu Statistik Operasional',
      description: 'Pantau jumlah pengajuan pending, total permohonan, pengajuan yang disetujui, dan pengajuan yang ditolak.',
      targetSelector: '[data-guide="approver-stat-cards"]',
      route: '/approver/dashboard',
      position: 'bottom',
    },
    {
      id: 'step_approver_quick_btn',
      title: '3. Tombol Quick Approval',
      description: 'Gunakan tombol ini untuk langsung menuju daftar pengajuan yang memerlukan tindakan persetujuan cepat.',
      targetSelector: '[data-guide="approver-quick-approval"]',
      route: '/approver/dashboard',
      position: 'bottom',
    },
    {
      id: 'step_pending_requests',
      title: '4. Halaman Pending Requests',
      description: 'Halaman ini menampilkan seluruh kartu pengajuan kendaraan dari staf yang menunggu keputusan Anda.',
      targetSelector: '[data-guide="approver-requests-list"]',
      route: '/approver/requests',
      position: 'top',
    },
    {
      id: 'step_approval_history',
      title: '5. Histori Keputusan Persetujuan',
      description: 'Akses riwayat lengkap seluruh permohonan yang telah Anda setujui maupun Anda tolak beserta Laporan CSV.',
      targetSelector: '[data-guide="approver-history-table"]',
      route: '/approver/history',
      position: 'top',
    },
    {
      id: 'step_notifications',
      title: '6. Pusat Notifikasi',
      description: 'Dapatkan pemberitahuan otomatis setiap kali ada permohonan kendaraan dinas baru dari anggota tim Anda.',
      targetSelector: '[data-guide="notifications"]',
      route: '/approver/notifications',
      position: 'bottom',
    },
    {
      id: 'step_profile',
      title: '7. Profil Pengguna',
      description: 'Kelola informasi pribadi dan data akun Anda di sini.\n\nAnda siap mengelola persetujuan kendaraan dinas!',
      targetSelector: '[data-guide="profile"]',
      route: '/approver/profile',
      position: 'right',
    },
  ],
};
