import type { TourConfig } from '../types';

export const employeeQuickTour: TourConfig = {
  id: 'employee_quick_tour',
  role: 'employee',
  title: 'Quick Tour Employee',
  description: 'Panduan lengkap cara menggunakan layanan pengajuan kendaraan dinas untuk Employee.',
  type: 'quick_tour',
  steps: [
    {
      id: 'step_dashboard',
      title: '1. Dashboard Employee',
      description: 'Selamat datang di Dashboard Employee! Di sini Anda dapat memantau status pengajuan kendaraan dan ringkasan perjalanan dinas.',
      targetSelector: '[data-guide="dashboard"]',
      route: '/employee/dashboard',
      position: 'right',
    },
    {
      id: 'step_upcoming_trips',
      title: '2. Jadwal Perjalanan Mendatang',
      description: 'Kartu ini menampilkan permohonan yang telah disetujui beserta nama driver dan unit mobil yang ditugaskan.',
      targetSelector: '[data-guide="employee-upcoming-trips"]',
      route: '/employee/dashboard',
      position: 'top',
    },
    {
      id: 'step_quick_actions',
      title: '3. Menu Aksi Cepat',
      description: 'Gunakan tombol pintar di sini untuk membuat pengajuan baru atau membuka daftar seluruh permohonan Anda dengan cepat.',
      targetSelector: '[data-guide="employee-quick-actions"]',
      route: '/employee/dashboard',
      position: 'left',
    },
    {
      id: 'step_create_request',
      title: '4. Buat Pengajuan Kendaraan',
      description: 'Gunakan menu ini untuk mengajukan permohonan armada kendaraan dinas baru beserta tanggal dan kota tujuan.',
      targetSelector: '[data-guide="create-request"]',
      route: '/employee/createrequest',
      position: 'right',
    },
    {
      id: 'step_my_requests',
      title: '5. Pantau Pengajuan Saya',
      description: 'Pantau daftar seluruh permohonan kendaraan yang telah Anda buat, lengkap dengan status persetujuan dari Kadep.',
      targetSelector: '[data-guide="my-requests"]',
      route: '/employee/myrequests',
      position: 'right',
    },
    {
      id: 'step_schedule',
      title: '6. Jadwal & Histori Perjalanan',
      description: 'Lihat rincian jadwal armada yang telah ditetapkan untuk Anda serta riwayat perjalanan dinas yang telah selesai.',
      targetSelector: '[data-guide="vehicle-schedule"]',
      route: '/employee/history',
      position: 'right',
    },
    {
      id: 'step_notifications',
      title: '7. Pusat Notifikasi',
      description: 'Tempat Anda menerima pemberitahuan langsung mengenai persetujuan pengajuan, penugasan driver, dan pembaruan sistem.',
      targetSelector: '[data-guide="notifications"]',
      route: '/employee/notifications',
      position: 'bottom',
    },
    {
      id: 'step_profile',
      title: '8. Profil Pengguna',
      description: 'Kelola informasi pribadi, NIK, serta preferensi akun Anda di sini.\n\nAnda siap mengajukan kendaraan dinas!',
      targetSelector: '[data-guide="profile"]',
      route: '/employee/profile',
      position: 'right',
    },
  ],
};
